all:
	arm-linux-gnueabi-gcc -I/src/ev3dev-c/source/ev3/ -O2  -std=gnu99 -W -Wall -c small_stadium_server.c -o small_stadium_server.o
	arm-linux-gnueabi-gcc small_stadium_server.o -Wall -lm -lev3dev-c -lpthread -lbluetooth -o small_stadium_server
	

